spring:
  application:
    name: test14_security
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: hello
    password: hello1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080